### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by PauloPhagula** [ntxuva/mopa-utils#17]
```
        Message type:       ERROR
        Location:           /srv/www/mopa-utils/vendor/flask/app.py:1587
        Module:             app
        Function:           log_exception
        Time:               2016-11-27 17:00:04

        Message:

        Exception on /tasks/send-daily-report [GET]

Traceback (most recent call last):
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/www/mopa-utils/mopa/tasks.py", line 345, in send_daily_report
    attachments=[config.REPORTS_DIR + '/' + f_name]
  File "/srv/www/mopa-utils/mopa/infrastructure.py", line 274, in send_mail
    raise Exception('Invalid Address "%s" in To' % mail_address)
TypeError: not all arguments converted during string formatting
```

**Comment by PauloPhagula** [comment]
Fixed in 41009370dd5cc9d1c63c3d0c07f360bf73569137
