### ISSUE TITLE
Error in email address validation

### ISSUE THREAD

**Issue by PauloPhagula** [ntxuva/mopa-utils#18]
Error occurs sometimes when running the daily report job
```
Message type:       ERROR
        Location:           /srv/www/mopa-utils/vendor/flask/app.py:1587
        Module:             app
        Function:           log_exception
        Time:               2016-12-07 17:00:04

        Message:

        Exception on /tasks/send-daily-report [GET]

Traceback (most recent call last):
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/www/mopa-utils/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/www/mopa-utils/mopa/tasks.py", line 346, in send_daily_report
    attachments=[config.REPORTS_DIR + '/' + f_name]
  File "/srv/www/mopa-utils/mopa/infrastructure.py", line 274, in send_mail
    raise Exception('Invalid Address "%s" in To' % str(mail_address))
Exception: Invalid Address "(False, u'spam@eggs.com')" in To
```

**Comment by PauloPhagula** [comment]
Fixed in 2bfba5a
