### ISSUE TITLE
Error running job: Send daily survey, due to: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

### ISSUE THREAD

**Issue by PauloPhagula** [ntxuva/mopa-utils#6]
```
Error running job: Send daily survey.
Error message:('Connection aborted.', gaierror(-2, 'Name or service not known')).
Exception Type: <class 'requests.exceptions.ConnectionError'>.
File name: tasks.py.
Line No: 33.
Traceback: Traceback (most recent call last):
  File "/home/psms1/sms-app/mopa/tasks.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/home/psms1/sms-app/mopa/tasks.py", line 458, in send_daily_survey
    db_sms = SMS.static_send(phone, constants.SMS_INTRO)
  File "/home/psms1/sms-app/mopa/models.py", line 128, in static_send
    sms.send()
  File "/home/psms1/sms-app/mopa/models.py", line 106, in send
    response = requests.get(SMS_END_POINT, params=payload)
  File "/home/psms1/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/psms1/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/psms1/.local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/psms1/.local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/psms1/.local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

**Comment by PauloPhagula** [comment]
This was a caused by a network error which made the HTTP request required to send SMS not reach endpoint. To circumvent this all network calls in project were wrapped with a retry and appropriate try-catch pair so errors don't bubble-up to the surface. 

Commit for above is ca2fd38bf1703c626d65d2bfadb4d4e81d432519
